export const categories = [
  { value: "electronics", label: "Electronics" },
  { value: "clothing", label: "Clothing & Apparel" },
  { value: "home-garden", label: "Home & Garden" },
  { value: "beauty-health", label: "Beauty & Health" },
  { value: "sports-outdoors", label: "Sports & Outdoors" },
  { value: "books-media", label: "Books & Media" },
  { value: "toys-games", label: "Toys & Games" },
  { value: "automotive", label: "Automotive" },
  { value: "groceries", label: "Groceries" },
  { value: "jewelry-watches", label: "Jewelry & Watches" },
  { value: "furniture", label: "Furniture" },
  { value: "office-supplies", label: "Office Supplies" },
  { value: "pet-supplies", label: "Pet Supplies" },
  { value: "baby-kids", label: "Baby & Kids" },
  { value: "arts-crafts", label: "Arts & Crafts" },
  { value: "musical-instruments", label: "Musical Instruments" },
  { value: "industrial", label: "Industrial Supplies" },
  { value: "travel-luggage", label: "Travel & Luggage" },
  { value: "shoes-footwear", label: "Shoes & Footwear" },
  { value: "computers", label: "Computers & Laptops" },
  { value: "phones-accessories", label: "Phones & Accessories" },
  { value: "kitchen-dining", label: "Kitchen & Dining" },
  { value: "tools-hardware", label: "Tools & Hardware" },
  { value: "collectibles", label: "Collectibles" },
  { value: "digital-products", label: "Digital Products" },
];
